export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',
  REFRESH_ACCESS_TOKEN: 'REFRESH_ACCESS_TOKEN',
  ADD_WISHLIST_ITEM: 'ADD_WISHLIST_ITEM',
  REMOVE_WISHLIST_ITEM: 'REMOVE_WISHLIST_ITEM',
};
